#!/bin/csh

#
# Instseq
#
# Instseqs product "seqcacheload" in the appropriate directory
#
# 1. cvs export -r seqcacheload-#-#-# seqcacheload
# 2. Copy Configuration.default Configuration
# 3. Edit Configuration
# 4. Instseq
#

cd `dirname $0` && source ./Configuration

if ( ! -d ${CACHEDIR} ) then
	mkdir ${CACHEDIR}
endif

if ( ! -d ${CACHEDATADIR} ) then
	mkdir ${CACHEDATADIR}
endif

if ( ! -d ${CACHELOGSDIR} ) then
	mkdir ${CACHELOGSDIR}
endif

